"""empty message

Revision ID: 3e7399269f37
Revises: 79f4de073be8
Create Date: 2019-05-12 17:08:23.975550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7399269f37'
down_revision = '79f4de073be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('recipe', 'course',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'course',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.drop_column('recipe', 'notes')
    # ### end Alembic commands ###
