"""empty message

Revision ID: 79f4de073be8
Revises: 
Create Date: 2019-05-12 05:39:48.446172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f4de073be8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('course', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'course')
    # ### end Alembic commands ###
