"""empty message

Revision ID: bb1bde0f009c
Revises: 3e7399269f37
Create Date: 2019-05-15 05:27:30.406155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1bde0f009c'
down_revision = '3e7399269f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_image', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_image')
    # ### end Alembic commands ###
